2023-10-01 01:09:21,208 - root - INFO - Unable to poll TPU GCE metadata: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/attributes/accelerator-type (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001F27A910D60>: Failed to resolve 'metadata.google.internal' ([Errno 11001] getaddrinfo failed)"))
2023-10-01 01:09:21,210 - root - INFO - Failed to detect number of TPUs: [WinError 3] The system cannot find the path specified: '/dev/vfio'
2023-10-01 01:14:06,519 - root - INFO - Unable to poll TPU GCE metadata: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/attributes/accelerator-type (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000243A58330D0>: Failed to resolve 'metadata.google.internal' ([Errno 11001] getaddrinfo failed)"))
2023-10-01 01:14:06,520 - root - INFO - Failed to detect number of TPUs: [WinError 3] The system cannot find the path specified: '/dev/vfio'
2023-10-01 01:21:20,467 - root - INFO - Unable to poll TPU GCE metadata: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/attributes/accelerator-type (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001C644D1F010>: Failed to resolve 'metadata.google.internal' ([Errno 11001] getaddrinfo failed)"))
2023-10-01 01:21:20,468 - root - INFO - Failed to detect number of TPUs: [WinError 3] The system cannot find the path specified: '/dev/vfio'
